baseURL = 'https://sendhiar.github.io/'
languageCode = 'en-us'
title = 'sendhiar-blog'
theme = "hugo-theme-console"
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  title = 'sendhiar-blog'
  description = "A vault of sendhiar's writing throughout the years. Talks about music, games, and stuff."
  images = ['images/sendhiar-profile.jpeg']